# Usa una imagen base de Java
FROM openjdk:17-jdk-slim

COPY target/backend-reto-0.0.1-SNAPSHOT.jar /app/backend-reto.jar

# Establece el directorio de trabajo
WORKDIR /app

# Expón el puerto que tu aplicación escucha
EXPOSE 9090

# Comando para ejecutar la aplicación
CMD ["java", "-jar", "backend-reto.jar"]
